# Generated by Django 5.0 on 2023-12-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tag',
            new_name='tags',
        ),
    ]
